server:
  port: 9012

spring:
  application:
    name: mall-job
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:nacos:8848}
      namespace: dev
      config:
        file-extension: yaml
        shared-dataids: common-mysql.yaml,common-redis.yaml
        refresh-enabled: true
        extension-configs[0]:
          dataId: mall-job.yaml
          group: DEFAULT_GROUP
          refresh: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:mall_order}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.mallcloud.malljob: DEBUG
