apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mallcloud-ingress
  namespace: mallcloud
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, X-Trace-Id"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  rules:
    - host: mallcloud.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mall-gateway
                port:
                  number: 9000
          - path: /nacos
            pathType: Prefix
            backend:
              service:
                name: mall-nacos
                port:
                  number: 8848
          - path: /sentinel
            pathType: Prefix
            backend:
              service:
                name: mall-sentinel
                port:
                  number: 8080
          - path: /zipkin
            pathType: Prefix
            backend:
              service:
                name: mall-zipkin
                port:
                  number: 9411
