# MallCloud 公共 Seata 配置
spring:
  cloud:
    alibaba:
      seata:
        # Seata 应用 id（TC 用来识别 RM）
        application-id: ${spring.application.name}
        # 事务组（对应 TC 配置的 vgroup-mapping）
        tx-service-group: mallcloud-tx-group
        # 关闭自动配置（手工使用 @GlobalTransactional）
        enable-auto-data-source-proxy: true
        config:
          type: nacos
          nacos:
            server-addr: ${NACOS_SERVER:nacos:8848}
            namespace: dev
            group: SEATA_GROUP
        registry:
          type: nacos
          nacos:
            server-addr: ${NACOS_SERVER:nacos:8848}
            namespace: dev
            group: SEATA_GROUP
            application: seata-server
