spring:
  application:
    name: mall-order
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        file-extension: yaml
        shared-configs:
          - data-id: common-mysql.yaml
            refresh: true
          - data-id: common-redis.yaml
            refresh: true
          - data-id: common-seata.yaml
            refresh: true
          - data-id: common-rocketmq.yaml
            refresh: true
          - data-id: common-sentinel.yaml
            refresh: true
