server:
  port: 9111

spring:
  application:
    name: mall-admin-biz
  config:
    import:
      - optional:nacos:common-redis.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:mall-admin-biz.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:nacos:8848}
      namespace: dev
      discovery:
        server-addr: ${NACOS_SERVER:nacos:8848}
        namespace: dev
        group: DEFAULT_GROUP
      config:
        file-extension: yaml
        shared-dataids: common-redis.yaml
        refresh-enabled: true
        extension-configs[0]:
          dataId: mall-admin-biz.yaml
          group: DEFAULT_GROUP
          refresh: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.mallcloud.malladminbiz: DEBUG
